### PR TITLE
Add the call photo to the Community page

### PR DESCRIPTION
**Pull request by leouieda**
Put it in the "Participate" section and move that to the top of the page to make sure people see it. Add a bit about some of the benefits of participating in open-source.

**Relevant issues/PRs:**

### CODE REVIEW

**Comment by leouieda** [comment]
@MGomezN @aguspesce what do you think about these changes? You both have keen eyes for this and are much better with the words than I am 🙂

**Comment by MGomezN** [comment]
Hello!
If I want to look at the changes rendered as a webpage do I have to fork this repository and then open the index locally in a browser?

Just looking at the code on the cellphone, the changes look awesome :)
You have a special talent to write in a way that everything feels super welcoming
conda install leo-friendly-style

**Comment by leouieda** [comment]
Thanks for the very kind words 😁

**Comment by MGomezN** [comment]
> Unfortunately, we don't have a way of previewing. It's possible to set something up for that but we never got around to it.
> 
> If you're only interested in seeing the changes, you don't need to fork since you won't be pushing anything. But since you have push access to this repository, you could push directly to it if you wanted to (just not `main` because we blocked it). To see changes in my branch, you can clone this repository (if you haven't already) and checkout the branch I'm using (you can see the branch name below the PR title above ☝🏾):
> 
> ```shell
> git clone git@github.com:fatiando/website.git
> cd website
> git checkout community-picture
> make serve
> ```

Thanks, @leouieda. I'll keep it in mind. Also, I need more practice with branches! :)

**Comment by leouieda** [comment]
Branches are awesome and one of the best parts of git 🙂

**Pull request merged**
