### PR TITLE
Add funding from Santi's Postdoc position

### PR DESCRIPTION
**Pull request by santisoler**
Add the salary from Santi's Postodoc position in GIF-UBC to the
Funding and Support section.

### CODE REVIEW

**Comment by santisoler** [comment]
@lheagy, I'm pinging you so you can give your approval of this PR. We talked about it, but wanted to make it more "formal" (or as formal as a PR could get 😁 )

**Review by lheagy — APPROVED** [review]
This looks great, thanks for adding Santi!!

**Comment by santisoler** [comment]
Thanks! Merging 🚀

**Comment by leouieda** [comment]
🤑 thanks for adding!

**Pull request merged**
